# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70a8fdd776391df2109fd8b4d3795b932f8dbd4a7a17cd7e4f3971b0640af3b08fa89a4403c8897a6c140ac0e80667daafdee8a036a8f17a1003c9aea747fb82

test:
  secret_key_base: adf7130bdf52aced76ac7d1af7885f5d0c701e608e432e70580b97a428988003272d197a514fb45aecd6f872885bb7f3f94db737d5934f4196c2987fbb1e7547

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
